name: cs fixer

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.YIISOFT_GITHUB_TOKEN }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"

      - name: Run Rector
        run: compose

      - name: Run PHP CS Fixer
        run: composer php-cs-fixer

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply PHP CS Fixer and Rector changes (CI)"
          file_pattern: '*.php'
          disable_globbing: true
