on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: yiisoft-di

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Checkout Yii Definitions
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: definitions-repo
          persist-credentials: false

      - name: Checkout Yii DI
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: di-repo
          repository: 'yiisoft/di'
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1
        with:
          working-directory: di-repo

      - name: Configure Yii Definitions usage
        working-directory: ${{ github.workspace }}/di-repo
        run: |
          composer config repositories.local path ../definitions-repo
          composer require yiisoft/definitions:@dev

      - name: Run tests with PhpUnit
        working-directory: ${{ github.workspace }}/di-repo
        run: vendor/bin/phpunit --colors=always
